### ISSUE TITLE
Kubeflow Component 사용법

### ISSUE THREAD

**Issue by Aiden-Jeon** [mlops-for-all/mlops-for-all.github.io#12]
1. Notebook
2. Volumes w\ Notebook

**Comment by anencore94** [comment]
1) central dashboard 접속 화면에서 좌측 탭이 각각 어디에 대응되는지 설명

2) notebooks
- jupyter lab instance, code server instance 등을 개별로 생성하고 사용할 수 있습니다. custom image 를 사용할 수 있습니다.
- vs code 와 연결해서 사용할 수 있습니다.

3) tensorboards
- 시각화(visualization) 기능 제공, 하지만 tensorboard 보다는 더 다양한 framework 에 대해 general 하게 사용할 수 있는 kfp components 의 visualization 과 mlflow 의 visualization 을 활용할 것이므로 mlops-for-all v1.0 에서는 생략

4) volumes
- notebooks 에서 사용할 volume 이나, kubeflow pipeline 에서 사용할 volume 을 본인 namespace 에 생성할 수 있음

5) models
- kserve model server 를 생성하고 관리할 수 있는 화면, v1.4.0 에서 처음 도입되었고 아직 미완성이므로 mlops-for-all v1.0 에서는 생략

6) experiments(AutoML)
- katib 관련 페이지로 HPO, NAS 등을 수행할 수 있고, mlops-for-all v1.0 에서는 생략

8) experiments(KFP) & Pipelines & Runs & Recurring Runs &  Artifacts & Executions
- Kubeflow 를 사용하는 주된 이유로 Pipeline 을 업로드하고 실행하며, 그 결과를 모아볼 수 있는 페이지입니다.
- 보다 자세한 내용은 3. Kubeflow 에서 자세한 사용법을 다룹니다.
