### ISSUE TITLE
`Edit this page on GitHub` 링크 404 에러

### ISSUE THREAD

**Issue by RyanKor** [mlops-for-all/mlops-for-all.github.io#67]
안녕하세요.

모두의 mlops 문서 학습 중에 footer 부분의 `Edit this page on Github` 링크 클릭 시, 404 에러가 발생해 이슈를 남깁니다.

## 1. 페이지 링크 클릭 화면
![image](https://user-images.githubusercontent.com/40455392/147825923-184b3d10-8a3d-437d-96ce-7607bb096567.png)

## 2. 링크 클릭시 404 에러 발생
![image](https://user-images.githubusercontent.com/40455392/147825993-3b0a9ddd-5bf1-4109-8603-adf888331d98.png)

해당 페이지의 링크가 github에서 제거된 것 같은데, 한 번 확인해주실 수 있는지 문의드리기 위해 issue를 남깁니다.

감사합니다.

**Comment by anencore94** [comment]
리포트 감사합니다! #70 에서 수정될 예정입니다.
