### ISSUE TITLE
`Kubeflow UI Guide` 페이지의 `Central Dashboard` 접속 관련 추가 내용 필요 문의

### ISSUE THREAD

**Issue by RyanKor** [mlops-for-all/mlops-for-all.github.io#69]
안녕하세요.

꾸준히 `모두의 mlops` 문서를 잘 읽고 실습 중인 사람입니다.

좋은 실습 자료를 제공해주셔서 대단히 감사합니다.

그런데 실습 관련 문의 사항이 있어 이슈를 남기게 되었습니다.

## 1. 문서 상황 구현 시도

![image](https://user-images.githubusercontent.com/40455392/148062964-7c9b8cef-b4f7-491b-afc0-bced36bd1592.png)

위의 이미지에서처럼 `Central Dashboard` 접속과 관련한 내용이 `모두의 mlops` 문서에 있는 것을 확인할 수 있습니다.

[해당 문서 링크](https://mlops-for-all.github.io/docs/kubeflow-dashboard-guide/intro/)

여기서 해당 문서 앞에 설명되어 있는 `Central Dashboard` 접속을 하기 위해서는 `kubectl port-forward --address <internal ip> svc/centraldashboard -n kubeflow 8082:80` 형태로 접속하게끔 안내가 되어 있었고, 초반에 해당 방법으로 접속하니, 아래와 같은 에러를 발견할 수 있었습니다.

## 2. 문서 내용 오인으로 CentralDashboard에서 에러 발생

![image](https://user-images.githubusercontent.com/40455392/148063473-4de34915-3d66-4bb2-bb1a-6c7e77283ed8.png)

이후, Kubeflow repo에 올라온 버그 리포트를 읽으면서 `istio-ingressgateway` 설정을 통해 접속하는 방법을 `모두의 mlops` 문서에서 안내했던 것이 생각이 났고, `kubectl port-forward --address <internal ip> svc/istio-ingressgateway -n istio-system 8080:80` 로 접속하니 정상적으로 jupyter notebook 생성 화면이 나오는 것을 확인할 수 있었습니다.

## 3. 에러 상황 해결

![image](https://user-images.githubusercontent.com/40455392/148063785-8865d06b-ca3c-416a-8400-7bb9f4c47a84.png)

그래서 문서를 실습하는 과정에서 다른 분들이 똑같은 상황을 겪을 수 있을 것 같은데, 해당 부분 내용을 조금 수정해서 `kubectl port-forward --address <internal ip> svc/istio-ingressgateway -n istio-system 8080:80` 로 접근해달라는 내용을 한 줄 추가하면 좋을 것 같은데, 혹시 PR을 보내도 되는지 문의드리고자 합니다.

## 4. Reference

- [Nested menu - "Sorry, /<endpoint>/ is not a valid page"](https://github.com/kubeflow/kubeflow/issues/6080)
- [[0.1.6] Deploying argoflow-aws](https://github.com/argoflow/argoflow-aws/issues/227)
- [Error: "Sorry, /jupyter/ is not a valid page"](https://github.com/kubeflow/kubeflow/issues/3615)

**Comment by anencore94** [comment]
안녕하세요! 말씀해주신대로 central dashboard svc 를 port-forwarding 한 경우에는 첨부해주신 스크린샷처럼 다른 페이지는 정상적으로 보이지 않는게 정상입니다.
탭의 위치를 보여주는 것이 목적이었는데, 현재 글의 흐름대로라면 반드시 오해할 수밖에 없을 것 같습니다.
각 component 사용법 설명에서 svc/centraldashboard 대신 svc/istio-ingressgateway -n istio-system 로 **변경**하는게 훨씬 좋을 것 같습니다.

편하실 때 PR 보내주시면 감사하겠습니다. 좋은 의견 감사합니다! @RyanKor

**Comment by RyanKor** [comment]
확인감사합니다. 추가 PR을 곧 작성해 업로드하도록 하겠습니다. @anencore94
