### ISSUE TITLE
[Question] API Deployment 파트 `Node_IP` 주소 설정 값의 클라우드 환경에서 설정 값 문의

### ISSUE THREAD

**Issue by RyanKor** [mlops-for-all/mlops-for-all.github.io#88]
안녕하세요.

모두의 MLops 실습을 수행 중인 개발자입니다.

이제 모두의 MLops 1회독을 거의 진행 완료했고, 배포 단계에 접했습니다.

배포 단계에서 한 가지 궁금한 점이 있어 문의드립니다.

![image](https://user-images.githubusercontent.com/40455392/149663151-83211b18-2f21-444d-96b7-fd6d77b5e21b.png)

위와 같이 노드 주소 값을 설정 중인데요.

해당 값의 주소 값을 설정할 때, 클라우드 환경이라면 클라우드에서 제공하고 있는 internal ip (또는 private ip) 로 대체해도 되는지 궁금합니다.

아마 여태까지 모두의 mlops 문서를 실습할 때의 정황상 `192.168.x.x` 사설 주소를 클라우드에서 설정할 때, 클라우드 자체에서 제공하던 internal ip로 대체서 사용을 했었는데, 제가 네트워크 지식이 짧다보니, 해당 부분을 문의드리게 됩니다.

추가로, 만약 사설 주소로 설정해도 된다면, 위의 이미지 내용에 대해 클라우드 상의 주소 값 설정 내용에 대한 부분을 PR 해도 되는지 함께 문의드립니다.

감사합니다.

**Comment by zamonia500** [comment]
이 다음 단계에서는, inference request를 날리게 되는데요. 클라우드에서 실습을 진행하게 된다면 local client -> cloud K8s server로 request를 날려야 합니다. 그렇게 하기 위해서는 ip만 갈아 끼우는 것으로는 부족하고, port-forward 같은 proxy 기능을 같이 사용해야 합니다.

[kubectl-port-forward-not-working-on-ec2-instance](https://stackoverflow.com/questions/63338776/kubectl-port-forward-not-working-on-ec2-instance) 다음 링크를 참고하셔서 port-forward 기능을 사용하시면 될 것 같습니다.

port-forward 말고도 external ip 사용과 같은 다른 방법을 사용하셔도 됩니다!
진행하신 내용 정리하여 PR 올려주신다면 클라우드 환경에서 실습하시는 분들에게 많은 도움이 될 것 같습니다! 환영이에요~

**Comment by RyanKor** [comment]
@zamonia500 감사합니다, 내용을 해결했으며, PR 진행했습니다
