### ISSUE TITLE
[Question] 로컬에서 모두의 MLops 환경 구성시, Docker 빌드 후, 쿠버네티스 실습하기

### ISSUE THREAD

**Issue by RyanKor** [mlops-for-all/mlops-for-all.github.io#97]
안녕하세요.

모두의 mlops 문서를 첫 실습은 빠르게 수행했고, 이제 2번째 내용을 쭉 읽어보면서 내용을 다져가려는 구독자입니다.

저희가 지금 안내해주신 내용대로면, Ubuntu OS에서 도커를 구성하는데요.

로컬에서 우분투를 파티션해서 구성하는 것도 가능하고, virtual box를 이용해 띄우는 것도 가능하지만 거의 대부분이 맥이나 윈도우를 사용하고 있고, m1 맥북에서는 아직 virtual box 지원이 안되기 때문에, 여러 환경적인 요소들을 감안해 사용자의 로컬 컴퓨터에서 도커를 사용해 ubuntu 환경을 구성하고, 거기에 쿠버네티스를 구성하는 세션을 문서 초반에 추가하는 것이 어떨지 한 번 제안드립니다.

좀 찾아봐야겠지만, 도커에 OS 이미지를 이용해 빌드하고, 그 안에서 다시 도커를 사용해 쿠버네티스를 사용하는 것인데, 문득 떠오른 아이디어라 maintainer 분들과 논의 후, 해당 환경을 구성해서 실습해 보고 싶습니다.

**Comment by anencore94** [comment]
@RyanKor 안녕하세요! 관심을 가져주시고 유용한 제안을 남겨주셔서 감사합니다 :+1: 

말씀해주신대로 맥이나 윈도우를 사용하는 유저가 많기에, 조금 더 접근성이 쉬운 환경 구성 방식을 제안하는 것도 좋을 것 같습니다.
개인적으로는 가장 통일성있게 수행할 수 있는 방법은 말씀하신 virtualbox 을 활용해 호스트의 os 에 우분투 이미지로 가상 머신을 띄우는 것일 것 같은데요, virtualbox 를 m1 맥북에서 지원하지 않는다면 vmwrae, qemu-kvm 등의 다른 가상머신 툴은 사용이 가능한지 우선 확인해보고 싶습니다.

제안해주신 두 번째 방법(`도커에 OS 이미지를 이용해 빌드하고, 그 안에서 다시 도커를 사용해 쿠버네티스를 사용하는 것`)은 [kind](https://kind.sigs.k8s.io/) 라는 tool 을 사용한다면 쉽게 가능합니다. (minikube, k3s 와 같은 레벨의 간소화된 쿠버네티스 설치 툴이라고 보시면 됩니다.)
[release v0.11.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.0) 부터 arm 도 지원을 하는걸로 보이는데요, kind 로 k8s cluster 를 구성해본 뒤, 그 안에서 저희가 사용하는 kubeflow, seldon-core 등이 정상적으로 동작하는지 테스트해볼 수 있을 것 같습니다.

또한, 실습에서 진행되는 방식인 `minikube start --driver=docker` 도 정확히 동일한 기능을 수행하고 있습니다. (linux kernel 기반 os 이미지로 도커 컨테이너를 하나 띄운 뒤, 그 내부에 kubeadm 을 이용해서 k8s 를 설치합니다.) 따라서 minikube binary 가 m1 을 지원한다면, minikube 역시 m1 notebook 에서 k8s 를 사용할 수 있을 것으로 보입니다.

**Comment by RyanKor** [comment]
@anencore94 안내해주신 vmware, qemu-kvm이 m1 맥북에서 활용가능한지 테스트 해보겠습니다.

그리고 `kind`라는 툴이 있는지 처음 알게 되었습니다. 요것도 자료를 좀 찾아보겠습니다.

정리만 잘 해놓으면 앞으로 모두의 mlops 문서가 더 많이 읽히게 될 것 같네요! 답변 감사합니다.

즐거운 명절 보내세요 :)

**Comment by RyanKor** [comment]
@anencore94 M1 맥북에 대한 virtualbox 지원 여부는 다음 애플 홈페이지의 discussion 페이지를 통해 확인할 수 있는데요. 

[링크](https://discussions.apple.com/thread/253292128)

virtualbox 와 vmware 모두 현재 x86 하드웨어에서만 지원이 되는 것으로 보입니다.

따라서, [UTM](https://cjlee38.github.io/etc/virtual_machine_in_m1) 이라는 툴을 이용해 설치해 가상 머신으로 쿠버네티스 실습을 해보도록 하겠습니다 (다행히 모두의 mlops 환경 설정이 될 것으로 보입니다)
